FROM --platform=linux/arm64/v8 node:18-alpine3.16
RUN apk add --no-cache alpine-conf && setup-timezone -z America/Chicago
RUN apk add --update nodejs npm
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
EXPOSE 3000

CMD ["npm", "run", "dev"]